on: push
name: Continous integration
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        php_version: [7.3.9, 7.2.22, 7.1.32]
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP version
        uses: khs1994-docker/actions-setup-php@master
        with:
          php_version: ${{ matrix.php_version }}
          args: |
            mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.default \
                    /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini || true
            set -x
            php -v
      - name: composer install
        uses: MilesChou/composer-action@master
        with:
          args: install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: phpunit
        uses: nathanheffley/laravel-phpunit-action@master

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: composer install
        uses: MilesChou/composer-action@master
        with:
          args: install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: phpinsights
        uses: stefanzweifel/laravel-phpinsights-action@v1.0.0
        with:
          args: -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80

  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_TITLE: Github Actions Notification
          SLACK_MESSAGE: Github Actions build finished successfuly
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    needs: [test, analyze]
