name: Pull Request Check
on:
  pull_request:
    types: [opened, edited]
jobs:
  started-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: homoluctus/slatify@master
        with:
          type: success
          job_name: '*Pull request opened/edited*'
          channel: '#github-actions-test'
          url: ${{ secrets.SLACK_WEBHOOK }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP version
        uses: khs1994-docker/actions-setup-php@master
        with:
          php_version: 7.3.9
          args: |
            mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.default \
                    /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini || true
            set -x
            php -v
      - name: composer install
        uses: MilesChou/composer-action@master
        with:
          args: install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: phpunit
        uses: nathanheffley/laravel-phpunit-action@master
      - name: Shaking finger
        if: failure()
        uses: thollander/actions-comment-pull-request@master
          with:
            message: '![finger.gif](https://github.com/jessfraz/shaking-finger-action/raw/master/finger.gif)'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: composer install
        uses: MilesChou/composer-action@master
        with:
          args: install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: phpinsights
        uses: stefanzweifel/laravel-phpinsights-action@v1.0.0
        with:
          args: -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80
      - name: Shaking finger
        if: failure()
        uses: thollander/actions-comment-pull-request@master
          with:
            message: '![finger.gif](https://github.com/jessfraz/shaking-finger-action/raw/master/finger.gif)'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
